**수치미분 ver.final - review**

In [1]:
import numpy as np

def numerical_derivative(f, x):
    delta_x = 1e-4
    # grad 변수는 입력 파라미터 x에 대해서 수치미분을 계산하고 그 결과값을 저장하는 변수
    # zeros_like를 통하여 생성되었기 때문에, x와 동일한 크기를 가짐
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

## 수치미분 예제
* 수치미분 함수 정의

In [12]:
import numpy as np

def numerical_derivative(f, x):    # 수치미분 debug version
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)
    print("debug 2. initial grad =", grad)
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. dix = ", idx, ", x[idx] = ", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

**수치미분 예제 - 1변수 함수 f(x) = x^2, f'(3.0)**<br>

수치미분에서 가장 먼저 해야 하는 것은 함수 f를 정의하는 것<br>
입력 파라미터 input_obj는 벡터나 행렬을 나타내는 numpy 객체. 수치미분 함수에서 두번째 입력 파라미터 x를 numpy 객체로 받기 때문이다.<br>

In [13]:
# 입력변수 1개인 함수 f(x) = x**2
def func1(input_obj):
    
    x = input_obj[0]
    
    return x**2

In [14]:
# x = 3.0 에서의 편미분 값
numerical_derivative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. dix =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]


array([6.])

**편미분 예제 - 2변수 함수 f(x, y) = 2x + 3xy + y^3, f'(1.0, 2.0)**<br>

각 1.0과 2.0을 가지는 numpy 벡터를 수치미분 함수로 함수 이름과 함께 넘겨줌<br>
결과는 입력 파라미터의 갯수만큼 while문이 두번 실행되고, 실행 시마다 미분값이 계산되어 grad에 저장

In [19]:
# 입력 변수 2개인 함수 f(x, y) = 2x + 3xy + y^3
def func1(input_obj):
    
    x = input_obj[0]
    y = input_obj[1]
    
    return ( 2*x + 3*x*y + np.power(y,3))

In [20]:
# (x,y) = (1.0, 2.0) 에서의 편미분 값
input = np.array([1.0, 2.0])
numerical_derivative(func1, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. dix =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
debug 3. dix =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]


array([ 8.        , 15.00000001])

**편미분 예제 - 4변수 함수 f(w, x, y, z) = wx + xyz + 3w + zy^2, f'(1.0, 2.0, 3.0, 4.0)** <br>

func1 함수의 입력 파라미터로 numpy의 벡터가 아닌, 2X2의 행렬을 입력 받음<br>

In [21]:
# 입력 변수 4개인 함수
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# input_obj 는 행렬
def func1(input_obj):
    
    w = input_obj[0, 0]
    x = input_obj[0, 1]
    y = input_obj[1, 0]
    z = input_obj[1, 1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y, 2))

In [22]:
# 입력을 2X2 행렬로 구성함
input = np.array([ [1.0, 2.0], [3.0, 4.0] ])

numerical_derivative(func1, input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. dix =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. dix =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. dix =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. dix =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])